version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: circleci/rust:latest

    # environment:
    #   # Set your codecov token if your repository is private.
    #   CODECOV_TOKEN: <your-token>
    #   TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      # - restore_cache:
      #     key: logtopus-cache
      # - run:
      #     name: Check formatting
      #     command: |
      #       rustfmt --version
      #       cargo fmt -- --write-mode=diff
      # - run:
      #     name: Nightly Build
      #     command: |
      #       rustup run nightly rustc --version --verbose
      #       rustup run nightly cargo --version --verbose
      #       rustup run nightly cargo build
      # - run:
      #     name: Stable Build
      #     command: cargo build
      - run:
          name: Test
          command: cargo test
      - run:
          name: Test
          command: cargo build --release
      - store_artifacts:
          path: target/release/logtopus
      # - run:
      #     name: Upload Coverage
      #     command: ./scripts/codecov.sh
      - save_cache:
          key: logtopus-cache
          paths:
            - "~/.cargo"
            - "./target"